Repository KccLast/FillIn, pull requests merged in 2024-10, with the labels that each got.

#70 feature: KMeans 군집화 UI 및 기능 구현
  .gitignore
  src/main/java/com/kcc/fillin/global/config/SecurityConfig.java
  src/main/java/com/kcc/fillin/statistic/controller/StatisticController2.java
  src/main/java/com/kcc/fillin/statistic/controller/StatisticRestController.java
  src/main/java/com/kcc/fillin/statistic/dao/StatisticMapper.java
  src/main/java/com/kcc/fillin/statistic/dto/QualitativeQuestionResponse.java
  src/main/java/com/kcc/fillin/statistic/service/StatisticService.java
  src/main/java/com/kcc/fillin/statistic/service/StatisticServiceImpl.java
  src/main/resources/mapper/StatisticMapper.xml
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/statistic/full.jsp
  src/main/webapp/WEB-INF/views/statistic/kmeans.jsp
  src/main/webapp/resources/css/statistic/kmeans.css
  src/main/webapp/resources/js/statistic/kmeans.js
Labels: 💫 feat, 🌈 frontend, 🔥 backend

#72 feature: KMeans 군집화 UI 및 기능 구현
  src/main/java/com/kcc/fillin/statistic/controller/StatisticController2.java
  src/main/webapp/WEB-INF/views/statistic/keyword.jsp
  src/main/webapp/WEB-INF/views/statistic/kmeans.jsp
  src/main/webapp/resources/js/statistic/kmeans.js
Labels: 💫 feat, 🔥 backend

#98 feature: 화면 수정
  src/main/webapp/WEB-INF/views/statistic/full.jsp
  src/main/webapp/WEB-INF/views/survey/project.jsp
  src/main/webapp/resources/css/question/question.css
  src/main/webapp/resources/js/question/questionEvent.js
Labels: 💫 feat, 🌈 frontend

#108 feature: 전체 통계 화면 UI 수정
  src/main/java/com/kcc/fillin/statistic/dto/QualitativeResponse.java
  src/main/java/com/kcc/fillin/statistic/dto/QuantitativeResponse.java
  src/main/resources/mapper/StatisticMapper.xml
  src/main/webapp/WEB-INF/views/statistic/full.jsp
  src/main/webapp/resources/common/statisticsNav.css
  src/main/webapp/resources/css/statistic/full.css
  src/main/webapp/resources/css/survey/post.css
  src/main/webapp/resources/js/statistic/full.js
Labels: 💫 feat, 🌈 frontend

#119 feature: 군집화 페이지 UI 수정
  src/main/webapp/WEB-INF/views/statistic/full.jsp
  src/main/webapp/WEB-INF/views/statistic/kmeans.jsp
  src/main/webapp/resources/css/statistic/kmeans.css
  src/main/webapp/resources/js/statistic/kmeans.js
Labels: 🌈 frontend

#122 design: gpt 자동 질문 생성 모달창, 마이페이지 css 수정
  src/main/resources/mapper/surveyMapper.xml
  src/main/webapp/resources/css/member/mypage.css
  src/main/webapp/resources/css/question/modal-autoQuestions.css
  src/main/webapp/resources/js/question/modal-autoQuestions.js
Labels: 🌈 frontend

#123 feature: 게시하기 UI 구현
  src/main/webapp/WEB-INF/views/survey/project.jsp
  src/main/webapp/resources/css/question/question.css
  src/main/webapp/resources/js/question/question.js
  src/main/webapp/resources/js/survey/surveyPost.js
Labels: 💫 feat, 🌈 frontend

#131 feature: 게시 / 공유하기 구현
  src/main/java/com/kcc/fillin/survey/controller/SurveyRestController.java
  src/main/java/com/kcc/fillin/survey/dao/SurveyDao.java
  src/main/java/com/kcc/fillin/survey/dto/PostSurveyRequest.java
  src/main/java/com/kcc/fillin/survey/dto/PostSurveyResponse.java
  src/main/java/com/kcc/fillin/survey/service/SurveyService.java
  src/main/java/com/kcc/fillin/survey/service/SurveyServiceImpl.java
  src/main/resources/mapper/surveyMapper.xml
  src/main/webapp/WEB-INF/views/survey/project.jsp
  src/main/webapp/resources/css/member/mypage.css
  src/main/webapp/resources/css/question/question.css
  src/main/webapp/resources/css/survey/post.css
  src/main/webapp/resources/js/survey/surveyPost.js
Labels: 💫 feat, 🌈 frontend, 🔥 backend
