Repository KccLast/FillIn, pull requests merged in 2024-09, with the labels that each got.

#5 feature: dockerfile 작성
  Dockerfile
Labels: 📝 docs, 🗃 infra

#7 feat: 공통 레이아웃 구현(헤더바, 사이드바)
  .metadata/.plugins/com.genuitec.eclipse.devstyle/recent.json
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/color-definitions-fix.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.buildship.ui-1231266899.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.egit.ui-1849137576.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.epp.mpc.ui.css--1027399938.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.jdt.ui-326703266.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.pde.spy.css-1231266899.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/splash-fix.css
  .metadata/.plugins/org.eclipse.core.resources/.projects/.org.eclipse.egit.core.cmp/.location
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/history.version
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.index
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.version
  .metadata/.plugins/org.eclipse.core.resources/.root/4.tree
  .metadata/.plugins/org.eclipse.core.resources/.safetable/org.eclipse.core.resources
  .metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
  .metadata/.plugins/org.eclipse.egit.ui/dialog_settings.xml
  .metadata/.plugins/org.eclipse.jdt.core/assumedExternalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/externalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/javaLikeNames.txt
  .metadata/.plugins/org.eclipse.jdt.core/nonChainingJarsCache
  .metadata/.plugins/org.eclipse.jdt.core/variablesAndContainers.dat
  .metadata/.plugins/org.eclipse.jdt.ui/OpenTypeHistory.xml
  .metadata/.plugins/org.eclipse.jdt.ui/QualifiedTypeNameHistory.xml
  .metadata/.plugins/org.eclipse.m2e.core.ui/dialog_settings.xml
  .metadata/.plugins/org.eclipse.m2e.core/workspaceState.ser
  .metadata/.plugins/org.eclipse.m2e.logback/logback.2.1.0.20221015-0744.xml
  .metadata/.plugins/org.eclipse.oomph.setup/workspace.setup
  .metadata/.plugins/org.eclipse.tips.ide/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.ide/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.intro/introstate
  .metadata/.plugins/org.eclipse.ui.workbench/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml
  .metadata/.plugins/org.eclipse.wst.jsdt.core/variablesAndContainers.dat
  .metadata/.plugins/org.eclipse.wst.jsdt.ui/OpenTypeHistory.xml
  .metadata/.plugins/org.eclipse.wst.jsdt.ui/QualifiedTypeNameHistory.xml
  .metadata/defender.check
  .metadata/version.ini
  .tern-project
  src/main/java/com/kcc/fillin/survey/SurveyController.java
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/resources/common/dashBoardNav.css
  src/main/webapp/resources/common/dashBoardNav.jsp
  src/main/webapp/resources/common/header.css
  src/main/webapp/resources/common/header.jsp
  src/main/webapp/resources/common/nav.css
  src/main/webapp/resources/common/nav.jsp
  src/main/webapp/resources/img/common/alarm.png
  src/main/webapp/resources/img/common/answerSheet.png
  src/main/webapp/resources/img/common/arrow.png
  src/main/webapp/resources/img/common/clustering.png
  src/main/webapp/resources/img/common/edit.png
  src/main/webapp/resources/img/common/keyword.png
  src/main/webapp/resources/img/common/logo.png
  src/main/webapp/resources/img/common/profile.png
  src/main/webapp/resources/img/common/totalStatistics.png
Labels: 🌈 frontend

#8 Update .gitignore
  .gitignore
Labels: ⚙️ chore

#9 [DOCS] main branch merged
  .gitignore
  .metadata/.plugins/com.genuitec.eclipse.devstyle/recent.json
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/color-definitions-fix.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.buildship.ui-1231266899.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.egit.ui-1849137576.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.epp.mpc.ui.css--1027399938.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.jdt.ui-326703266.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/colors-org.eclipse.pde.spy.css-1231266899.css
  .metadata/.plugins/com.genuitec.eclipse.ui.common.platform/splash-fix.css
  .metadata/.plugins/org.eclipse.core.resources/.projects/.org.eclipse.egit.core.cmp/.location
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/history.version
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.index
  .metadata/.plugins/org.eclipse.core.resources/.root/.indexes/properties.version
  .metadata/.plugins/org.eclipse.core.resources/.root/4.tree
  .metadata/.plugins/org.eclipse.core.resources/.safetable/org.eclipse.core.resources
  .metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
  .metadata/.plugins/org.eclipse.egit.ui/dialog_settings.xml
  .metadata/.plugins/org.eclipse.jdt.core/assumedExternalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/externalFilesCache
  .metadata/.plugins/org.eclipse.jdt.core/javaLikeNames.txt
  .metadata/.plugins/org.eclipse.jdt.core/nonChainingJarsCache
  .metadata/.plugins/org.eclipse.jdt.core/variablesAndContainers.dat
  .metadata/.plugins/org.eclipse.jdt.ui/OpenTypeHistory.xml
  .metadata/.plugins/org.eclipse.jdt.ui/QualifiedTypeNameHistory.xml
  .metadata/.plugins/org.eclipse.m2e.core.ui/dialog_settings.xml
  .metadata/.plugins/org.eclipse.m2e.core/workspaceState.ser
  .metadata/.plugins/org.eclipse.m2e.logback/logback.2.1.0.20221015-0744.xml
  .metadata/.plugins/org.eclipse.oomph.setup/workspace.setup
  .metadata/.plugins/org.eclipse.tips.ide/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.ide/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.intro/introstate
  .metadata/.plugins/org.eclipse.ui.workbench/dialog_settings.xml
  .metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml
  .metadata/.plugins/org.eclipse.wst.jsdt.core/variablesAndContainers.dat
  .metadata/.plugins/org.eclipse.wst.jsdt.ui/OpenTypeHistory.xml
  .metadata/.plugins/org.eclipse.wst.jsdt.ui/QualifiedTypeNameHistory.xml
  .metadata/defender.check
  .metadata/version.ini
  .tern-project
  src/main/java/com/kcc/fillin/survey/SurveyController.java
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/resources/common/dashBoardNav.css
  src/main/webapp/resources/common/dashBoardNav.jsp
  src/main/webapp/resources/common/header.css
  src/main/webapp/resources/common/header.jsp
  src/main/webapp/resources/common/nav.css
  src/main/webapp/resources/common/nav.jsp
  src/main/webapp/resources/img/common/alarm.png
  src/main/webapp/resources/img/common/answerSheet.png
  src/main/webapp/resources/img/common/arrow.png
  src/main/webapp/resources/img/common/clustering.png
  src/main/webapp/resources/img/common/edit.png
  src/main/webapp/resources/img/common/keyword.png
  src/main/webapp/resources/img/common/logo.png
  src/main/webapp/resources/img/common/profile.png
  src/main/webapp/resources/img/common/totalStatistics.png
Labels: 🗃 infra, ⚙️ chore

#11 fix: 공통 컴포넌트 수정(헤더바, 사이드바)(#10)
  src/main/java/com/kcc/fillin/survey/controller/SurveyController.java
  src/main/webapp/WEB-INF/views/survey/dashboard.jsp
  src/main/webapp/resources/common/header.css
  src/main/webapp/resources/common/nav.css
  src/main/webapp/resources/css/survey/dashboard.css
  src/main/webapp/resources/img/common/plusButton.png
Labels: 🐛 bug, 🌈 frontend
